config/routes.rb
Rede::Application.routes.draw do
  resources :mergulhos

  resources :mergulhadores

  resources :escolas

  devise_for :usuarios
  
  devise_scope :usuario do
    get "/logout" => "devise/sessions#destroy"
  end
  
  root :to => 'welcome#index'

end

app/models/escola.rb
class Escola < ActiveRecord::Base
  has_one :usuario, :as => :cadastro
  has_and_belongs_to_many :mergulhadores, :join_table => 'escolas_mergulhadores'
  
  validates :responsavel, :length => { :within =>  3..45, :message => " deve ter entre 3 e 45 caracteres." }
  validates :nome, :length => { :within =>  3..60, :message => " deve ter entre 3 e 60 caracteres." }
  validates :localizacao, :length => { :within =>  3..80, :message => " deve ter entre 3 e 80 caracteres." }
end

app/models/escolas_mergulhadores.rb
class EscolasMergulhadores < ActiveRecord::Base
  belongs_to :escola
  belongs_to :mergulhador
end

app/models/mergulhador.rb
class Mergulhador < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "165x148>" }
  
  has_one :usuario, :as => :cadastro
  has_and_belongs_to_many :escolas
  has_many :mergulhos
  
  validates :nome, :length => { :within =>  3..45, :message => " deve ter entre 3 e 45 caracteres." }
  validates :sexo, :presence => { :message => " é obrigatório." }
end

app/models/mergulho.rb
class Mergulho < ActiveRecord::Base
  belongs_to :mergulhador
  
  validates :nome_local, :local_mergulho, :length => { :within =>  3..45, :message => " deve ter entre 3 e 45 caracteres." }
  validates :temperatura, :length => { :within =>  3..20, :message => " deve ter entre 3 e 20 caracteres." }
  validates :profundidade, :numericality => true
  
  acts_as_gmappable
      def gmaps4rails_address
          local_mergulho
      end
      def gmaps4rails_infowindow
        "<h4>#{nome_local}</h4>" << "<h4>#{local_mergulho}</h4>"
      end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :tipo
  
  belongs_to :cadastro, :polymorphic => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def atualiza(fk, tipo, pk)
    ActiveRecord::Base.connection.execute("update usuarios set cadastro_id=#{fk}, cadastro_type='#{tipo}' WHERE id=#{pk}")
  end
end

app/controllers/escolas_controller.rb
class EscolasController < ApplicationController
  before_filter :authenticate_usuario!, :load
  
  def load
    @escola = Escola.new
    @mergulhadores = Mergulhador.find(:all)
  end
  
  def find
    @escola = Escola.find(current_usuario.cadastro_id)
  end

  def show
    find
  end

  def new
  end

  def create
    @escola = Escola.new(params[:escola])
    if @escola.save
      atualiza(@escola.id, @escola.class, current_usuario.id)
      redirect_to @escola, :notice => "O registro foi inserido com sucesso."
    else
      render :action => 'new'
    end
  end

  def edit
    find
  end

  def update
    find
    if @escola.update_attributes(params[:escola])
      redirect_to @escola, :notice  => "O registro foi atualizado com sucesso."
    else
      render :action => 'edit'
    end
  end

end

app/controllers/mergulhadores_controller.rb
class MergulhadoresController < ApplicationController
  before_filter :authenticate_usuario!, :load
  
  def load
    @mergulhador = Mergulhador.new
    @escolas = Escola.find(:all)
  end
  
  def find
    @mergulhador = Mergulhador.find(current_usuario.cadastro_id)
  end

  def show
    find
  end

  def new
  end

  def create
    @mergulhador = Mergulhador.new(params[:mergulhador])
    if @mergulhador.save
      atualiza(@mergulhador.id, @mergulhador.class, current_usuario.id)
      redirect_to @mergulhador, :notice => "O registro foi inserido com sucesso."
    else
      render :action => 'new'
    end
  end

  def edit
    find
  end

  def update
    find
    if @mergulhador.update_attributes(params[:mergulhador])
      redirect_to @mergulhador, :notice  => "O registro foi atualizado com sucesso."
    else
      render :action => 'edit'
    end
  end

end

app/controllers/mergulhos_controller.rb
class MergulhosController < ApplicationController
  before_filter :authenticate_usuario!, :load
  
  def load
    @mergulhos = Mergulho.where("mergulhador_id = #{current_usuario.cadastro_id}")
    @mergulho = Mergulho.new
    @mergulhador = Mergulhador.find(current_usuario.cadastro_id)
  end
  
  def find
    @mergulho = Mergulho.find(params[:id])
  end

  def index
    @json = Mergulho.all.to_gmaps4rails
  end

  def show
    find
  end

  def new
  end

  def edit
    find
  end

  def create
    @mergulho = Mergulho.new(params[:mergulho])
    if @mergulho.save
      redirect_to @mergulho, :notice => "O registro foi inserido com sucesso."
    else
      render :action => 'new'
    end 
  end

  def update
    find
    if @mergulho.update_attributes(params[:mergulho])
      redirect_to @mergulho, :notice  => "O registro foi atualizado com sucesso."
    else
      render :action => 'edit'
    end   
  end

  def destroy
    @mergulho = Mergulho.find(params[:id])
    @mergulho.destroy
    redirect_to(mergulhos_url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_usuario!
  
  def index
    if (current_usuario.tipo == 2) && (current_usuario.cadastro_id == nil)
      redirect_to '/mergulhadores/new'
    elsif (current_usuario.tipo == 2) && (current_usuario.cadastro_id != nil)
      redirect_to "/mergulhadores/#{current_usuario.cadastro_id}"
    elsif (current_usuario.tipo == 1) && (current_usuario.cadastro_id == nil)
      redirect_to '/escolas/new'
    else
      redirect_to "/escolas/#{current_usuario.cadastro_id}"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/escolas_helper.rb
module EscolasHelper
end

app/helpers/mergulhadores_helper.rb
module MergulhadoresHelper
end

app/helpers/mergulhos_helper.rb
module MergulhosHelper
end

app/views/escolas/_detail.html.erb
<div class="meus_alunos">
	<p>Alunos Vinculados</p>
	<ul>
		<% @escola.mergulhadores.each do |mergulhador| %>
			<li><%= mergulhador.nome %></li>
		<% end %>
	</ul>
</div>
<div class="detalhe">
	<div class="box_detalhe">
		<p>
		  <b>Nome:</b>
		  <%= @escola.nome %>
		</p>
		<p>
		  <b>Data da fundação:</b>
		  <%= I18n.localize(@escola.fundacao, :format => :default) %>  
		</p>
		<p>
		  <b>Responsável:</b>
		  <%= @escola.responsavel %>
		</p>
		<p>
		  <b>Localização:</b>
		  <%= @escola.localizacao %>
		</p>
	</div>
	<%= link_to 'Principal', @escola, :class => "link_principal" %>
	<%= link_to 'Atualizar meus dados', edit_escola_path(@escola), :class => "link_edit" %>
</div>

app/views/escolas/_form.html.erb
<p class="title_cabecalho">Cadastro da escola</p>
<%= form_for(@escola) do |f| %>
  <% if @escola.errors.any? %>
    <div id="error_explanation">
      <h4>O registro não pode ser salvo verifique os erros abaixo:</h4>
      <ul>
      <% @escola.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :nome %>
    <%= f.text_field :nome %>
    <%= f.label :fundacao, 'Fundação' %>
    <%= f.date_select :fundacao, :start_year => 1920, :end_year => Time.now.year %>
    <%= f.label :responsavel, 'Responsável' %>
    <%= f.text_field :responsavel %>
    <%= f.label :localizacao, 'Localização' %>
    <%= f.text_field :localizacao %>
    <%= f.label :mergulhadores %>
	  <%= f.collection_select :mergulhador_ids, @mergulhadores, :id, :nome, {}, :multiple => true %> 
    <%= f.submit 'Enviar' %>
<% end %>

app/views/escolas/edit.html.erb
<%= render 'detail' %>
<div class="novo_usuario">
	<%= render 'form' %>
</div>

app/views/escolas/new.html.erb
<div class="novo_usuario">
	<% if (current_usuario.tipo == 1) && (current_usuario.cadastro_id == nil) -%>
		<%= render 'form' %>
	<% else -%>
		<p><%= link_to "Voltar para os dados da escola", "/escolas/#{current_usuario.cadastro_id}" %></p>
	<% end %>
</div>

app/views/escolas/show.html.erb
<% unless notice.blank? -%>
	<p id="notice"><%= notice %></p>
<% end %>
<%= render 'detail' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mergulho & Cia</title>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
  <%= yield :head %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
	<div id="corpo">
		<div id="espaco">
			<% if usuario_signed_in? -%>
	  		<%= link_to 'Logout', '/logout', :class => "link_logout" %>
	  	<% end -%>
			<%= yield %>
			<%= yield :scripts %>
		</div>
	</div>
</body>
</html>

app/views/mergulhadores/_detail.html.erb
<div id="lateral">
	<div class="minhas_escolas">
		<p>Minhas escolas</p>
		<ul>
			<% @mergulhador.escolas.each do |escola| %>
				<li><%= escola.nome %></li>
			<% end %>
		</ul>
	</div>
	<div class="meus_colegas">
		<p>Meus colegas</p>
	</div>
</div>
<div class="detalhe">
	<div class="box_detalhe">
		<% unless @mergulhador.avatar_file_name.blank? -%>
			<%= image_tag @mergulhador.avatar.url(:thumb) %>
		<% end %>
		<p>
		  <b>Nome:</b>
		  <%= @mergulhador.nome %>
		</p>
		<p>
		  <b>Sexo:</b>
		  <%= @mergulhador.sexo == 'M'? 'Masculino' : 'Feminino' %>
		</p>
		<p>
		  <b>Data nascimento:</b>
		  <%= I18n.localize(@mergulhador.data_nascimento, :format => :default) %>  
		</p>
	</div>
	<%= link_to 'Principal', @mergulhador, :class => "link_principal" %>
	<%= link_to 'Atualizar meus dados', edit_mergulhador_path(@mergulhador), :class => "link_edit" %>
	<%= link_to "Listar meus mergulhos", mergulhos_path, :class => "link_listar_mergulho" %>
	<%= link_to "Inserir novo mergulho", new_mergulho_path, :class => "link_novo_mergulho" %>
</div>

app/views/mergulhadores/_form.html.erb
<p class="title_cabecalho">Cadastro do mergulhador</p>
<%= form_for @mergulhador, :html => { :multipart => true } do |f| %>
  <% if @mergulhador.errors.any? %>
    <div id="error_explanation">
      <h4>O registro não pode ser salvo verifique os erros abaixo:</h4>
      <ul>
      <% @mergulhador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :nome %>
    <%= f.text_field :nome %>
    <%= f.label :sexo %>
    <%= f.select :sexo, [['Seleciona uma opção',''], ['Masculino', 'M'],['Feminino', 'F']] %>
    <%= f.label :data_nascimento, 'Data de Nascimento' %>
    <%= f.date_select :data_nascimento, :start_year => 1920, :end_year => Time.now.year %>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
    <%= f.label :escolas %>
	  <%= f.collection_select :escola_ids, @escolas, :id, :nome, {}, :multiple => true %> 
    <%= f.submit 'Enviar' %>
<% end %>

app/views/mergulhadores/edit.html.erb
<%= render 'detail' %>
<div class="novo_usuario">
	<%= render 'form' %>
</div>

app/views/mergulhadores/new.html.erb
<div class="novo_usuario">
	<% if (current_usuario.tipo == 2) && (current_usuario.cadastro_id == nil) -%>
		<%= render 'form' %>
	<% else -%>
		<p><%= link_to "Voltar para os dados do mergulhador", "/mergulhadores/#{current_usuario.cadastro_id}" %></p>
	<% end %>
</div>

app/views/mergulhadores/show.html.erb
<% unless notice.blank? -%>
	<p id="notice"><%= notice %></p>
<% end %>
<%= render 'detail' %>

app/views/mergulhos/_form.html.erb
<p class="title_cabecalho">Cadastro de mergulho</p>
<%= form_for(@mergulho) do |f| %>
  <% if @mergulho.errors.any? %>
    <div id="error_explanation">
     <h4>O registro não pode ser salvo verifique os erros abaixo:</h4>
      <ul>
      <% @mergulho.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  	<%= f.hidden_field :mergulhador_id, :value => current_usuario.cadastro_id %>
    <%= f.label :data, 'Data do mergulho' %>
    <%= f.date_select :data %>
    <%= f.label :hora_inicio, 'Hora de início' %>
    <%= f.time_select :hora_inicio %>
    <%= f.label :hora_fim, 'Hora do Fim' %>
    <%= f.time_select :hora_fim %>
    <%= f.label :nome_local, 'Nome da localidade' %>
    <%= f.text_field :nome_local %>
    <%= f.label :local_mergulho, 'Local do Mergulho' %>
    <%= f.text_field :local_mergulho %>
    <%= f.label :profundidade %>
    <%= f.text_field :profundidade %>
    <%= f.label :temperatura %>
    <%= f.text_field :temperatura %>
    <%= f.submit 'Enviar' %>
<% end %>

app/views/mergulhos/edit.html.erb
<%= render '/mergulhadores/detail' %>
<div class="novo_usuario">
	<%= render 'form' %>
</div>

app/views/mergulhos/index.html.erb
<%= render '/mergulhadores/detail' %>
<div class="listagem">
	<table>
	  <tr>
	    <th>Data do mergulho</th>
	    <th>Horário</th>
	    <th>Nome da localidade</th>
	    <th>Local do Mergulho</th>
	    <th>Profundidade</th>
	    <th colspan="3" width="7%"></th>
	  </tr>
		<% @mergulhos.each do |mergulho| %>
		  <tr>
		    <td><%= I18n.localize(mergulho.data, :format => :default) %>  </td>
		    <td><%= I18n.localize(mergulho.hora_inicio, :format => :short) %> às <%= I18n.localize(mergulho.hora_fim, :format => :short) %></td>
		    <td><%= mergulho.nome_local %></td>
		    <td><%= mergulho.local_mergulho %></td>
		    <td><%= mergulho.profundidade %></td>
		    <td><%= link_to image_tag("ico_detalhe_16.png", :alt=>"Detalhar", :title=>"Detalhar"), mergulho %></td>
				<td><%= link_to image_tag("ico_altera_16.png", :alt=>"Editar", :title=>"Editar"), edit_mergulho_path(mergulho) %></td>
				<td><%= link_to image_tag("ico_apaga_16.png", :alt=>"Excluir", :title=>"Excluir"), mergulho, :confirm => 'Deseja realmente excluir esse registro?', :method => :delete %></td>
		  </tr>
		<% end %>
	</table>
	<% unless @mergulhos.blank? -%>
		<%= gmaps4rails(@json) %>
	<% end %>
</div>

app/views/mergulhos/new.html.erb
<%= render '/mergulhadores/detail' %>
<div class="novo_usuario">
	<%= render 'form' %>
</div>

app/views/mergulhos/show.html.erb
<% unless notice.blank? -%>
	<p id="notice"><%= notice %></p>
<% end %>
<%= render '/mergulhadores/detail' %>
<div class="meu_mergulho">
	<p>
	  <b>Data do mergulho:</b>
	  <%= I18n.localize(@mergulho.data, :format => :default) %>  
	</p>
	<p>
	  <b>Horário:</b>
	  <%= I18n.localize(@mergulho.hora_inicio, :format => :short) %> às <%= I18n.localize(@mergulho.hora_fim, :format => :short) %>
	</p>
	<p>
	  <b>Nome da localidade:</b>
	  <%= @mergulho.nome_local %>
	</p>
	<p>
	  <b>Local do Mergulho:</b>
	  <%= @mergulho.local_mergulho %>
	</p>
	<p>
	  <b>Profundidade:</b>
	  <%= @mergulho.profundidade %>
	</p>
	<p>
	  <b>Coordenadas:</b>
	  <%= @mergulho.longitude %>, <%= @mergulho.latitude %>
	</p>
	<p>
	  <b>Temperatura:</b>
	  <%= @mergulho.temperatura %>
	</p>
</div>